name: Generate Activity Graph

permissions:
  contents: write

on:
  push:
    paths:
      - 'README.md'
  schedule:
    - cron: '0 0 * * *'   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Ashutosh00710/github-readme-activity-graph@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: 'activity-graph.svg'

      - name: Commit and push activity graph
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: 'chore: update activity graph'
          add: 'activity-graph.svg'
